Develop to Master
MistySOM/meta-mistysom pull request #31
Opened 2023-07-10 19:08 UTC by matinlotfali

2023-07-10 19:29 UTC, mistyron approved these changes

2023-07-10 19:32 UTC, mistyron requested changes
Please add a PR description

2023-07-10 22:39 UTC, mistyron approved these changes
LGHTM :+1:

2023-07-12 19:42 UTC, matinlotfali commented
@mistyron FYI, I am also having the Fix devicetree append patch into master

2023-07-12 19:46 UTC, merged